language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

script:
  - mkdir build && cd build
  - if [ $TRAVIS_OS_NAME == windows ]; then 
  -   cmake -G "Visual Studio 15 2017 Win64" ..
  -   # MSBuild
  - else
  -   cmake -DCMAKE_BUILD_TYPE=Release ..
  -   make
  - fi