language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

# before_install:
#   - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y libuv1-dev ; fi
#   - if [ $TRAVIS_OS_NAME == osx ]; then sudo brew install libuv ; fi

addons:
  apt:
    packages:
      - libuv1-dev
  homebrew:
    packages:
      - libuv
    update: true

script:
  - mkdir build && cd build
  - if [ $TRAVIS_OS_NAME == linux ];   then cmake -DCMAKE_BUILD_TYPE=Release .. && make && ./liblua/test/liblua_Test && ./cmod/gb2312/gb2312-test ; fi
  - if [ $TRAVIS_OS_NAME == osx ];     then cmake -DCMAKE_BUILD_TYPE=Release .. && make && ./liblua/test/liblua_Test && ./cmod/gb2312/gb2312-test ; fi
  - if [ $TRAVIS_OS_NAME == windows ]; then cmake -G "Visual Studio 15 2017 Win64" .. ; fi
  - # TODO: MSBuild for windows
  - cd ../luawithlib && mkdir build && cd build
  - if [ $TRAVIS_OS_NAME == linux ];   then cmake -DCMAKE_BUILD_TYPE=Release .. && make ; fi
  - if [ $TRAVIS_OS_NAME == osx ];     then cmake -DCMAKE_BUILD_TYPE=Release .. && make ; fi
  - if [ $TRAVIS_OS_NAME == windows ]; then cmake -G "Visual Studio 15 2017 Win64" .. ; fi
  - # TODO: MSBuild for windows
